### ISSUE TITLE
 ObjectNotFound: diffsync_cluster XXX not present in LocalStore

### ISSUE THREAD

**Issue by TravelTrexIT** [h4ndzdatm0ld/nautobot-ssot-vsphere#23]
### Environment
* Python version:  3.10.4
* Nautobot version:  1.4.2
* nautobot-ssot-vsphere version:  0.1.2

### Expected Behavior
After i added another Cluster and filled it with data, i re-run the sync with the nautobot-ssot-vsphere plugin. It should ignore the manually added Cluster and sync the data between the configured vSphere Cluster and nautobot.

### Observed Behavior
nautobot-ssot-vsphere prints out the following error:

`
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 327, in run
    self.sync_data()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_vsphere/jobs.py", line 156, in sync_data
    dest.load()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_nautobot.py", line 201, in load
    self.load_data()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_nautobot.py", line 197, in load_data
    self.load_virtual_machines()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_nautobot.py", line 129, in load_virtual_machines
    diffsync_cluster = self.get(self.diffsync_cluster, virtual_machine.cluster.name)
  File "/opt/nautobot/lib/python3.10/site-packages/diffsync/__init__.py", line 639, in get
    return self.store.get(model=obj, identifier=identifier)
  File "/opt/nautobot/lib/python3.10/site-packages/diffsync/store/local.py", line 49, in get
    raise ObjectNotFound(f"{modelname} {uid} not present in {str(self)}")
diffsync.exceptions.ObjectNotFound: diffsync_cluster **another_cluster** not present in LocalStore
`

### Steps to Reproduce
1. Add another cluster and fill it with data (e.g., add a virtual machine)
2. Re-run the sync
3. Receive the error message

I tried also the following:
- using Tags only (same result)
- using Cluster filter (same result)

**Comment by TravelTrexIT** [comment]
@h4ndzdatm0ld Hey. Do you had any time to take a look into this? Do you need more information?

**Comment by h4ndzdatm0ld** [comment]
Hey there @TravelTrexIT ! -  I am having a hard time reproducing. Can you share a snippet of the plugin_config for ssot_vsphere in your nautobot_config.py file as well?

**Comment by TravelTrexIT** [comment]
@h4ndzdatm0ld Sure!

`PLUGINS = ["nautobot_ssot","nautobot_ssot_vsphere","nautobot_device_lifecycle_mgmt","nautobot_cable_utils","nautobot_ui_plugin","nautobot_bulk_connect"]
PLUGINS_CONFIG = {
    "nautobot_ssot_vsphere": {
        "VSPHERE_URI": "https://xxx.traveltrex.local",
        "VSPHERE_USERNAME": "nautobot.vsphere@xxx",
        "VSPHERE_PASSWORD": "xxx",
        "VSPHERE_VERIFY_SSL": False,
        "DEFAULT_USE_CLUSTERS": True,
        "VSPHERE_TYPE": "VMWare vSphere",
        "ENFORCE_CLUSTER_GROUP_TOP_LEVEL": False,
        "DEFAULT_CLUSTER_NAME": "vSphere Default Cluster",
    },
`

**Comment by h4ndzdatm0ld** [comment]
I'm still unable to recreate the issue. Is the new cluster part of the same datacenter (ClusterGroup?) Is it a new CluterGroup? Is the new VM tagged with the ssot-vsphere tag?.

Are you able to recreate it, if you delete the cluster and try again?

**Comment by TravelTrexIT** [comment]
Maybe we had a missunderstanding. The Cluster is not part of any vSphere Cluster at all - i am not using the plugin to sync the data with it. I created the cluster on my own in nautobot, added the virtual machines and then observed, that the diffsync of the ssot-vsphere plugins tries to sync/delete it on the next try. 

It really doesnt matter if i give it another tag, another clustergroup, another cluster or change the behavior of the plugin at all: it all the time tries to sync it and gives me the error. If i enforce it (by ignoring the tag), it deletes the cluster from nautobot, thus removing it totally from nautobot.

**Comment by h4ndzdatm0ld** [comment]
Thanks for the clarification! I was just able to recreate.

```
   raise ObjectNotFound(f"{modelname} {uid} not present in {self.name}")
diffsync.exceptions.ObjectNotFound: diffsync_cluster TestCluster not present in NautobotDiffSync
```

Will take a peek in the next couple days. Planning on making a new release soon.
Appreciate you using the plugin!

**Comment by h4ndzdatm0ld** [comment]
Hi @TravelTrexIT The only way I was able to recreate was by:
1. Doing a sync with vSphere and populating all the data through the plugin's SSoT capabilities.
2. Creating a new Cluster, adding it to a group and adding VM's into it.
3. Running the sync with a filter of only syncing the data from step 1.

The error here was that I failed to filter virtual machines and the attempt to sync everything failed as diffsync didn't know about the additional clusters. This is now resolved and this behavior will allow users to properly only sync with the necessary filters.

Additionally, by **_design_**, the SSoT/Diffsync will absolutely delete anything that is not present from the external source. Meaning, if you do not provide a filter at sync runtime, anything that is not found in data from vSphere, after running the diffsync evaluation will be removed from Nautobot. This is the reason why these plugins provide the filtering capabilities, for users to be able to only sync the data from their source and ignore the local data that is present in the database from other sources. The only way around it is by ensuring you run your sync with the Cluster filter or Tag filter to ensure you don't delete any other data in Nautobot. Hopefully that makes sense.

Please test out the branch associated with this issue and retry syncs, with the filter applied that points to your cluster (more specific) from vSphere or tagged objects to capture anything associated with your vSphere environment - and let me know if that works better !

**Comment by TravelTrexIT** [comment]
Hi @h4ndzdatm0ld.

Thank you very much. I tried it out, but it seems for our case it still have some problems. I think the main reason here is that our vSphere Center has **two** Clusters. Unfortunartely, i cannot just filter one of them. But just to make sure that it would work, tried the dry run with just one Cluster filtered, and it worked flawless. If i still use the plugin with the tag filtering, it shows me the correct amound number of Virtual Machines with the tag, but it still throws me the error about the cluster which is not party of the SSOT Cluster. 

Example with Tag filtering: 

![image](https://user-images.githubusercontent.com/2297439/196135562-3f56965e-ca64-401b-84a6-096a7c7f78de.png)

Is it possible to filter multiple Clusters or create multiple jobs with different Clusters to filter on? 

I really appreciate the work you put into this! Thank you so much.

**Comment by TravelTrexIT** [comment]
@h4ndzdatm0ld Ok, i figured out that i forget one single Virtual Machine who had misconfigured a wrong Tag. I corrected it and now the data is synced. I am sorry for the trouble which I stated in the last comment. 

Still though, if I sync, the job itself returns "Failed", but the data is synced and nothing is deleted. The output of the log is the following:

![image](https://user-images.githubusercontent.com/2297439/196141859-08314989-ae7b-41db-a7b1-def72380e42d.png)

**Comment by h4ndzdatm0ld** [comment]
Wooo! progress. I will get this merged and close this issue. This seems like something different is causing this behavior. The error is raised here: https://github.com/h4ndzdatm0ld/nautobot-ssot-vsphere/blob/ff0c3f35657925b7c0b7f4b2ec20fd8f76055984/nautobot_ssot_vsphere/diffsync/adapters/adapter_nautobot.py#L67

Do you mind creating a separate issue for that?

**Comment by TravelTrexIT** [comment]
@h4ndzdatm0ld Sure! Thank you so much for your work. I really love the plugin and appreciate all the work you put into this.
